import type { User, Task, Notification } from "@/types"

export const mockUsers: User[] = [
  {
    id: 1,
    name: "Alex Morgan",
    email: "alex@todo-app.com",
    password: "password123",
    phone: "+1 (555) 123-4567",
    country: "US",
    role: "Manager",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    id: 2,
    name: "Sophia Chen",
    email: "sophia@todo-app.com",
    password: "password123",
    phone: "+1 (555) 234-5678",
    country: "CA",
    role: "Admin",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    id: 3,
    name: "Marcus Johnson",
    email: "marcus@todo-app.com",
    password: "password123",
    phone: "+1 (555) 345-6789",
    country: "UK",
    role: "Staff",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  {
    id: 4,
    name: "Zara Williams",
    email: "zara@todo-app.com",
    password: "password123",
    phone: "+1 (555) 456-7890",
    country: "AU",
    role: "Staff",
    avatar: "https://randomuser.me/api/portraits/women/67.jpg",
  },
  {
    id: 5,
    name: "Liam Patel",
    email: "liam@todo-app.com",
    password: "password123",
    phone: "+1 (555) 567-8901",
    country: "DE",
    role: "Customer",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    id: 6,
    name: "Olivia Rodriguez",
    email: "olivia@todo-app.com",
    password: "password123",
    phone: "+1 (555) 678-9012",
    country: "FR",
    role: "Customer",
    avatar: "https://randomuser.me/api/portraits/women/90.jpg",
  },
  {
    id: 7,
    name: "Demo User",
    email: "demo@todo-app.com",
    password: "password123",
    phone: "+1 (555) 987-6543",
    country: "US",
    role: "Admin",
    avatar: "https://randomuser.me/api/portraits/lego/1.jpg",
  },
]

export const mockTasks: Task[] = [
  {
    id: 1,
    title: "Design New Landing Page",
    description: "Create a modern, responsive landing page design with improved conversion elements",
    category: "Design",
    priority: "High",
    dueDate: "2023-07-15",
    completed: false,
    assignedTo: 1,
    subtasks: [
      "Research competitor sites",
      "Create wireframes",
      "Design mobile version",
      "Prepare assets for developers",
    ],
    notes: "Focus on minimalist design with clear CTAs",
    created: "2023-06-30",
    timer: 0,
    lastEdited: "2023-07-02T14:30:00.000Z",
  },
  {
    id: 2,
    title: "Implement Authentication System",
    description: "Set up OAuth and email authentication for the new application",
    category: "Development",
    priority: "High",
    dueDate: "2023-07-10",
    completed: false,
    assignedTo: 2,
    subtasks: [
      "Configure OAuth providers",
      "Implement email verification",
      "Set up password reset flow",
      "Write tests",
    ],
    notes: "Use Firebase Authentication for the MVP version",
    created: "2023-06-28",
    timer: 0,
    lastEdited: "2023-07-01T09:15:00.000Z",
  },
  {
    id: 3,
    title: "Create Content Strategy",
    description: "Develop a comprehensive content strategy for Q3 marketing campaigns",
    category: "Marketing",
    priority: "Medium",
    dueDate: "2023-07-22",
    completed: false,
    assignedTo: 4,
    subtasks: ["Audience research", "Content calendar", "Channel strategy", "Success metrics"],
    notes: "Align with product launch timeline",
    created: "2023-07-01",
    timer: 0,
  },
  {
    id: 4,
    title: "User Testing Sessions",
    description: "Organize and conduct user testing for the beta version of the mobile app",
    category: "Research",
    priority: "Medium",
    dueDate: "2023-07-28",
    completed: false,
    assignedTo: 3,
    subtasks: ["Recruit participants", "Prepare test scenarios", "Conduct sessions", "Analyze feedback"],
    notes: "Focus on core user flows and new features",
    created: "2023-07-02",
    timer: 0,
  },
  {
    id: 5,
    title: "API Security Audit",
    description: "Conduct a comprehensive security review of all API endpoints",
    category: "Development",
    priority: "High",
    dueDate: "2023-07-08",
    completed: false,
    assignedTo: 1,
    subtasks: ["Review authentication", "Check rate limiting", "Test for vulnerabilities", "Document findings"],
    notes: "Use OWASP API Security Top 10 as reference",
    created: "2023-06-25",
    timer: 0,
  },
  {
    id: 6,
    title: "Social Media Campaign",
    description: "Plan and execute summer promotion campaign across all social platforms",
    category: "Marketing",
    priority: "Medium",
    dueDate: "2023-07-30",
    completed: true,
    assignedTo: 4,
    subtasks: ["Create visual assets", "Write copy", "Schedule posts", "Prepare paid promotion"],
    notes: "Budget: $3,500 for paid promotion",
    created: "2023-06-20",
    timer: 3600,
  },
  {
    id: 7,
    title: "Fix Payment Processing Bug",
    description: "Resolve the issue with international payment processing failures",
    category: "Development",
    priority: "High",
    dueDate: "2023-07-05",
    completed: true,
    assignedTo: 3,
    subtasks: ["Reproduce issue", "Debug payment flow", "Implement fix", "Test with multiple currencies"],
    notes: "Affects approximately 15% of international transactions",
    created: "2023-07-01",
    timer: 7200,
  },
  {
    id: 8,
    title: "Investor Pitch Deck",
    description: "Create compelling pitch deck for the upcoming funding round",
    category: "Business",
    priority: "High",
    dueDate: "2023-07-18",
    completed: false,
    assignedTo: 2,
    subtasks: ["Market analysis", "Financial projections", "Product roadmap", "Team overview"],
    notes: "Target: $5M Series A round",
    created: "2023-07-01",
    timer: 0,
  },
  {
    id: 9,
    title: "Performance Optimization",
    description: "Improve application loading speed and overall performance",
    category: "Development",
    priority: "Medium",
    dueDate: "2023-08-05",
    completed: false,
    assignedTo: 1,
    subtasks: ["Audit current performance", "Optimize images", "Implement lazy loading", "Reduce bundle size"],
    notes: "Target: 20% improvement in page load time",
    created: "2023-07-02",
    timer: 0,
  },
  {
    id: 10,
    title: "Customer Satisfaction Survey",
    description: "Design and distribute quarterly customer satisfaction survey",
    category: "Research",
    priority: "Low",
    dueDate: "2023-08-15",
    completed: false,
    assignedTo: 4,
    subtasks: ["Design questions", "Set up survey tool", "Distribution plan", "Analysis framework"],
    notes: "Compare results with Q1 survey",
    created: "2023-06-28",
    timer: 0,
  },
  {
    id: 11,
    title: "Code Review Process",
    description: "Establish new code review guidelines and process",
    category: "Development",
    priority: "Low",
    dueDate: "2023-07-25",
    completed: true,
    assignedTo: 3,
    subtasks: ["Research best practices", "Draft guidelines", "Team feedback", "Documentation"],
    notes: "Focus on efficiency without compromising quality",
    created: "2023-07-01",
    timer: 1800,
  },
  {
    id: 12,
    title: "Office Equipment Upgrade",
    description: "Research and purchase new equipment for the design team",
    category: "Operations",
    priority: "Low",
    dueDate: "2023-08-10",
    completed: true,
    assignedTo: 2,
    subtasks: ["Assess needs", "Research options", "Get quotes", "Place orders"],
    notes: "Budget: $12,000",
    created: "2023-06-15",
    timer: 5400,
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 1,
    title: "Task Deadline Approaching",
    message: 'Task "Design New Landing Page" is due in 2 days',
    read: false,
  },
  {
    id: 2,
    title: "New Task Assigned",
    message: 'You have been assigned to "Implement Authentication System"',
    read: false,
  },
  {
    id: 3,
    title: "Task Completed",
    message: '"Social Media Campaign" was marked as complete',
    read: false,
  },
]
